# Generated by Django 5.0.3 on 2024-04-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reciperesult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperesult',
            name='user',
        ),
    ]
